{
 "title": "Portfolio New",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "invested_jpy", "query": "${VAR_INVESTED_JPY}" }
  ]
 },
 "panels": [
  {
   "title": "Total asset",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "USD",
     "query": "SELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)"
    },
    {
     "alias": "JPY",
     "query": "SELECT sum(JPY) as JPY FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)"
    }
   ]
  },
  {
   "title": "Portfolio performance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Recent USD",
     "query": "SELECT (last(USD)-first(USD)) from (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    },
    {
     "alias": "Recent JPY",
     "query": "SELECT (last(JPY)-first(JPY)) from (\nSELECT sum(JPY) as JPY FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    },
    {
     "alias": "ALL JPY",
     "query": "SELECT (last(JPY)-$invested_jpy) from (\nSELECT sum(JPY) as JPY FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    }
   ]
  },
  {
   "title": "Portfolio performance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Recent USD",
     "query": "SELECT (last(USD)-first(USD))/first(USD) from (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    },
    {
     "alias": "Recent JPY",
     "query": "SELECT (last(JPY)-first(JPY))/first(JPY) from (\nSELECT sum(JPY) as JPY FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    },
    {
     "alias": "ALL JPY",
     "query": "SELECT (last(JPY)-$invested_jpy) /$invested_jpy from (\nSELECT sum(JPY) as JPY FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    }
   ]
  },
  {
   "title": "FX (JPY/USD)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "JPY/USD",
     "query": "SELECT JPY/USD FROM (\nSELECT sum(USD) as USD, sum(JPY) as JPY FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    }
   ]
  },
  {
   "title": "Total Asset (USD)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Total",
     "query": "SELECT USD FROM (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    }
   ]
  },
  {
   "title": "PnL (USD)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "PnL",
     "query": "SELECT difference(USD) as USD FROM (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n)"
    }
   ]
  },
  {
   "title": "Assets per symbol (USD)",
   "type": "timeseries",
   "description": "Assets < $1 are not shown",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_symbol",
     "query": "SELECT USD from (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s), symbol\n)\nWHERE USD > 1\nGROUP BY symbol"
    }
   ]
  },
  {
   "title": "Assets per symbol (USD)",
   "type": "stat",
   "description": "Assets < $1 are not shown",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_symbol",
     "query": "SELECT USD from (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE time > now() -1h\nGROUP BY TIME(10s), symbol\n) \nWHERE USD > 1\nGROUP BY symbol"
    }
   ]
  },
  {
   "title": "Assets per symbol (USD)",
   "type": "piechart",
   "description": "Assets < $1 are not shown",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_symbol",
     "query": "SELECT last(USD) from (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s), symbol\n) \nWHERE time > now() - 1h and USD > 1\nGROUP BY symbol"
    }
   ]
  },
  {
   "title": "Assets per location (USD)",
   "type": "piechart",
   "description": "Assets < $1 are not shown",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "exchange/$tag_exchange",
     "query": "SELECT last(USD) from (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter and location = 'cefi'\nGROUP BY TIME(10s), exchange\n) \nWHERE time > now() - 1h and USD > 1\nGROUP BY exchange"
    },
    {
     "alias": "$tag_chain/wallet",
     "query": "SELECT last(USD) from (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter and location = 'defi' and type = 'wallet'\nGROUP BY TIME(10s), chain\n) \nWHERE time > now() - 1h\nGROUP BY chain"
    },
    {
     "alias": "$tag_chain/$tag_protocol",
     "query": "SELECT last(USD) from (\nSELECT sum(USD) as USD FROM portfolio.infinite.portfolio\nWHERE $timeFilter and location = 'defi' and type = 'position'\nGROUP BY TIME(10s), chain, protocol\n) \nWHERE time > now() - 1h\nGROUP BY chain, protocol"
    }
   ]
  },
  {
   "title": "Assets per exchange & symbol",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "SELECT last(amount) as amount, last(USD) as USD, last(JPY) as JPY from (\nSELECT sum(amount) as amount, sum(USD) as USD, sum(JPY) as JPY FROM portfolio.infinite.portfolio\nWHERE $timeFilter\nGROUP BY TIME(10s)\n) \nWHERE time > now() - 1h\nGROUP BY location, exchange, type, chain, symbol"
    }
   ]
  }
 ]
}